### ISSUE TITLE
Can You add a bill of materials and instructions on how to build it?

### ISSUE THREAD

**Issue by Pythone** [emente/arduino-cricut#1]

**Comment by splorp** [comment]
Like @Pythone, I’m very interested in whether this is an buildable project or not.

Are there any details available? Has anyone made this work?

**Comment by Pythone** [comment]
I am going to guesstimate based on code

**Comment by Pythone** [comment]
3 dials, not sure how many stepper motors or servos, an arduino(already knew based on the name), page ca. 15cm * 30cm., and we would need to look further into the project

**Comment by emente** [comment]
This is an arduino-based control software for the Cricut Personal machine with broken CPUs and not a complete cutting machine. I will clarify the readme.
